export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAUILER = 'REGISTER_FAUILER';

export const OTP_LOADING = 'OTP_LOADING';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAUILER = 'OTP_FAUILER';

export const OTP_FORGOT_PASSWORD_LOADING = 'OTP_FORGOT_PASSWORD_LOADING';
export const OTP_FORGOT_PASSWORD_SUCCESS = 'OTP_FORGOT_PASSWORD_SUCCESS';
export const OTP_FORGOT_PASSWORD_FAUILER = 'OTP_FORGOT_PASSWORD_FAUILER';
export const OTP_FORGOT_PASSWORD_REMOVE = 'OTP_FORGOT_PASSWORD_REMOVE';

export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAUILER = 'CHANGE_PASSWORD_FAUILER';
export const CHANGE_PASSWORD_REMOVE = 'CHANGE_PASSWORD_REMOVE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAUILER = 'LOGIN_FAUILER';

export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAUILER = 'FORGOT_PASSWORD_FAUILER';
export const FORGOT_PASSWORD_REMOVE = 'FORGOT_PASSWORD_REMOVE';

export const LOGIN_STATE_RESTORE_REQUEST = 'LOGIN_STATE_RESTORE_REQUEST';
export const LOGIN_STATE_RESTORE = 'LOGIN_STATE_RESTORE';
export const LOGOUT_Status = 'LOGOUT_Status';

export const SET_FCMTOKEN = 'SET_FCMTOKEN';

export const PRODUCT_DATA_LOADING = 'PRODUCT_DATA_LOADING';
export const PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS';
export const PRODUCT_DATA_FAUILER = 'PRODUCT_DATA_FAUILER';
export const PRODUCT_DATA_REMOVE = 'PRODUCT_DATA_REMOVE';

export const CART_DATA_LOADING = 'CART_DATA_LOADING';
export const CART_DATA_SUCCESS = 'CART_DATA_SUCCESS';
export const CART_DATA_FAUILER = 'CART_DATA_FAUILER';
export const CART_DATA_REMOVE = 'CART_DATA_REMOVE';

export const CART_ADD_DATA_LOADING = 'CART_ADD_DATA_LOADING';
export const CART_ADD_DATA_SUCCESS = 'CART_ADD_DATA_SUCCESS';
export const CART_ADD_DATA_FAUILER = 'CART_ADD_DATA_FAUILER';
export const CART_ADD_DATA_REMOVE = 'CART_ADD_DATA_REMOVE';

export const CART_REMOVE_DATA_LOADING = 'CART_REMOVE_DATA_LOADING';
export const CART_REMOVE_DATA_SUCCESS = 'CART_REMOVE_DATA_SUCCESS';
export const CART_REMOVE_DATA_FAUILER = 'CART_REMOVE_DATA_FAUILER';
export const CART_REMOVE_DATA_REMOVE = 'CART_REMOVE_DATA_REMOVE';

export const CART_INCREASE_DATA_LOADING = 'CART_INCREASE_DATA_LOADING';
export const CART_INCREASE_DATA_SUCCESS = 'CART_INCREASE_DATA_SUCCESS';
export const CART_INCREASE_DATA_FAUILER = 'CART_INCREASE_DATA_FAUILER';
export const CART_INCREASE_DATA_REMOVE = 'CART_INCREASE_DATA_REMOVE';

export const CART_DECREASE_DATA_LOADING = 'CART_DECREASE_DATA_LOADING';
export const CART_DECREASE_DATA_SUCCESS = 'CART_DECREASE_DATA_SUCCESS';
export const CART_DECREASE_DATA_FAUILER = 'CART_DECREASE_DATA_FAUILER';
export const CART_DECREASE_DATA_REMOVE = 'CART_DECREASE_DATA_REMOVE';

export const FAVORITE_PRODUCT_GET_LOADING = 'FAVORITE_PRODUCT_GET_LOADING';
export const FAVORITE_PRODUCT_GET_SUCCESS = 'FAVORITE_PRODUCT_GET_SUCCESS';
export const FAVORITE_PRODUCT_GET_FAUILER = 'FAVORITE_PRODUCT_GET_FAUILER';

export const ADD_FAVORITE_PRODUCT_LOADING = 'ADD_FAVORITE_PRODUCT_LOADING';
export const ADD_FAVORITE_PRODUCT_SUCCESS = 'ADD_FAVORITE_PRODUCT_SUCCESS';
export const ADD_FAVORITE_PRODUCT_FAUILER = 'ADD_FAVORITE_PRODUCT_FAUILER';
export const ADD_FAVORITE_PRODUCT_REMOVE = 'ADD_FAVORITE_PRODUCT_REMOVE';

export const REMOVE_FAVORITE_PRODUCT_LOADING =
  'REMOVE_FAVORITE_PRODUCT_LOADING';
export const REMOVE_FAVORITE_PRODUCT_SUCCESS =
  'REMOVE_FAVORITE_PRODUCT_SUCCESS';
export const REMOVE_FAVORITE_PRODUCT_FAUILER =
  'REMOVE_FAVORITE_PRODUCT_FAUILER';
export const REMOVE_FAVORITE_PRODUCT_REMOVE = 'REMOVE_FAVORITE_PRODUCT_REMOVE';

export const GET_USERDATA = 'GET_USERDATA';
export const REMOVE_USERDATA = 'REMOVE_USERDATA';

export const HISTORY_PRODUCT_GET_LOADING = 'HISTORY_PRODUCT_GET_LOADING';
export const HISTORY_PRODUCT_GET_SUCCESS = 'HISTORY_PRODUCT_GET_SUCCESS';
export const HISTORY_PRODUCT_GET_FAUILER = 'HISTORY_PRODUCT_GET_FAUILER';

export const CHECKOUT_PRODUCT_LOADING = 'CHECKOUT_PRODUCT_LOADING';
export const CHECKOUT_PRODUCT_SUCCESS = 'CHECKOUT_PRODUCT_SUCCESS';
export const CHECKOUT_PRODUCT_FAUILER = 'CHECKOUT_PRODUCT_FAUILER';
export const CHECKOUT_PRODUCT_REMOVE = 'CHECKOUT_PRODUCT_REMOVE';
